name: Widget tests & code analysis

on: [push, pull_request]

# https://admcpr.com/continuous-integration-for-flutter-with-github-actions/
jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        channel: stable
    - name: Version
      run: flutter doctor -v
    - name: Install dependencies
      run: flutter pub get
    - name: Format
      run: dart format -o none --set-exit-if-changed .
    - name: Linter
      run: flutter analyze
    - name: Test
      run: flutter test
